ccflags-y += -Idrivers/media/huawei/camera
ccflags-y += -Idrivers/media/huawei/camera/sensor
ccflags-y += -Idrivers/media/huawei/camera/pmic
ccflags-y += -Idrivers/media/huawei/camera/platform

obj-y += sensor_common.o
obj-y += sensor/
