#ifndef __SOC_MDC_INTERFACE_H__
#define __SOC_MDC_INTERFACE_H__ 
#ifdef __cplusplus
    #if __cplusplus
        extern "C" {
    #endif
#endif
#ifndef __SOC_H_FOR_ASM__
#define SOC_MDC_AIF_CH_CTL_0_ADDR(base) ((base) + (0x0000UL))
#define SOC_MDC_MIF_CTRL_D0_ADDR(base) ((base) + (0x0010UL))
#define SOC_MDC_CTL_MUTEX_RCH0_ADDR(base) ((base) + (0x0030UL))
#define SOC_MDC_RCH0_OV_OEN_ADDR(base) ((base) + (0x0160UL))
#define SOC_MDC_RCH0_FLUSH_EN_ADDR(base) ((base) + (0x0100UL))
#define SOC_MDC_MOD0_DBG_ADDR(base) ((base) + (0x0200UL))
#define SOC_MDC_DMA_OFT_X0_ADDR(base) ((base) + (0x0000UL))
#define SOC_MDC_DFC_DISP_SIZE_ADDR(base) ((base) + (0x0100UL))
#define SOC_MDC_CTL_MUTEX_WCH0_ADDR(base) ((base) + (0x0020UL))
#define SOC_MDC_WCH0_OV_IEN_ADDR(base) ((base) + (0x01A0UL))
#define SOC_MDC_WCH0_FLUSH_EN_ADDR(base) ((base) + (0x0120UL))
#define SOC_MDC_MOD8_DBG_ADDR(base) ((base) + (0x0220UL))
#define SOC_MDC_SCF_EN_HSCL_STR_ADDR(base) ((base) + (0x0200UL))
#define SOC_MDC_PCSC_IDC0_ADDR(base) ((base) + (0x0400UL))
#define SOC_MDC_POST_CLIP_DISP_SIZE_ADDR(base) ((base) + (0x0480UL))
#define SOC_MDC_CSC_IDC0_ADDR(base) ((base) + (0x0500UL))
#define SOC_MDC_MOD1_DBG_ADDR(base) ((base) + (0x0204UL))
#define SOC_MDC_MOD2_DBG_ADDR(base) ((base) + (0x0208UL))
#define SOC_MDC_MOD6_DBG_ADDR(base) ((base) + (0x0218UL))
#define SOC_MDC_MOD9_DBG_ADDR(base) ((base) + (0x0224UL))
#define SOC_MDC_MOD12_DBG_ADDR(base) ((base) + (0x0230UL))
#define SOC_MDC_CMDLIST_SWRST_ADDR(base) ((base) + (0x0738UL))
#define SOC_MDC_CTL_CLEAR_ADDR(base) ((base) + (0x0058UL))
#define SOC_MDC_CTL_STATUS_ADDR(base) ((base) + (0x0068UL))
#define SOC_MDC_DMA_BUF_DBG0_ADDR(base) ((base) + (0x838UL))
#define SOC_MDC_DMA_BUF_DBG1_ADDR(base) ((base) + (0x83CUL))
#define SOC_MDC_CTL_MUTEX_RCH1_ADDR(base) ((base) + (0x0034UL))
#define SOC_MDC_CTL_MUTEX_RCH2_ADDR(base) ((base) + (0x0038UL))
#define SOC_MDC_CTL_MUTEX_RCH6_ADDR(base) ((base) + (0x0048UL))
#define SOC_MDC_CTL_MUTEX_WCH1_ADDR(base) ((base) + (0x0024UL))
#define SOC_MDC_CMDLIST_CH_CTRL_ADDR(base,i) ((base) + (0x0004+0x40*(i)))
#define SOC_MDC_CMDLIST_CH_STATUS_ADDR(base,i) ((base) + (0x0008+0x40*(i)))
#define SOC_MDC_CMDLIST_CH_INTS_ADDR(base,i) ((base) + (0x001C+0x40*(i)))
#define SOC_MDC_CMDLIST_ADDR_MASK_EN_ADDR(base) ((base) + (0x0718UL))
#define SOC_MDC_CMDLIST_CH_STAAD_ADDR(base,i) ((base) + (0x000C+0x40*(i)))
#define SOC_MDC_CMDLIST_ADDR_MASK_DIS_ADDR(base) ((base) + (0x071CUL))
#define SOC_MDC_CTL_ST_SEL_ADDR(base) ((base) + (0x0074UL))
#define SOC_MDC_CTL_SW_ST_ADDR(base) ((base) + (0x0070UL))
#define SOC_MDC_AIF_CH_CTL_1_ADDR(base) ((base) + (0x0020UL))
#define SOC_MDC_AIF_CH_CTL_2_ADDR(base) ((base) + (0x0040UL))
#define SOC_MDC_AIF_CH_CTL_6_ADDR(base) ((base) + (0x00C0UL))
#define SOC_MDC_AIF_CH_CTL_8_ADDR(base) ((base) + (0x0100UL))
#define SOC_MDC_AIF_CH_CTL_9_ADDR(base) ((base) + (0x0120UL))
#define SOC_MDC_AIF_CH_CTL_10_ADDR(base) ((base) + (0x0140UL))
#define SOC_MDC_AIF_CH_CTL_CMD_ADDR(base) ((base) + (0x0830UL))
#define SOC_MDC_MMU_ID_ATTR_NS_0_ADDR(base) ((base) + (0x0580UL))
#define SOC_MDC_MMU_ID_ATTR_NS_1_ADDR(base) ((base) + (0x0584UL))
#define SOC_MDC_MMU_ID_ATTR_NS_2_ADDR(base) ((base) + (0x0588UL))
#define SOC_MDC_MMU_ID_ATTR_NS_6_ADDR(base) ((base) + (0x0598UL))
#define SOC_MDC_MMU_ID_ATTR_NS_8_ADDR(base) ((base) + (0x05A0UL))
#define SOC_MDC_MMU_ID_ATTR_NS_9_ADDR(base) ((base) + (0x05A4UL))
#define SOC_MDC_MMU_ID_ATTR_NS_10_ADDR(base) ((base) + (0x05A8UL))
#define SOC_SMMUv3_TBU_SMMU_TBU_SWID_CFG_ADDR(base,m) ((base) + ((m)*0x4+0x100UL))
#define SOC_MDC_MMU_ID_ATTR_NS_13_ADDR(base) ((base) + (0x05B4UL))
#else
#define SOC_MDC_AIF_CH_CTL_0_ADDR(base) ((base) + (0x0000))
#define SOC_MDC_MIF_CTRL_D0_ADDR(base) ((base) + (0x0010))
#define SOC_MDC_CTL_MUTEX_RCH0_ADDR(base) ((base) + (0x0030))
#define SOC_MDC_RCH0_OV_OEN_ADDR(base) ((base) + (0x0160))
#define SOC_MDC_RCH0_FLUSH_EN_ADDR(base) ((base) + (0x0100))
#define SOC_MDC_MOD0_DBG_ADDR(base) ((base) + (0x0200))
#define SOC_MDC_DMA_OFT_X0_ADDR(base) ((base) + (0x0000))
#define SOC_MDC_DFC_DISP_SIZE_ADDR(base) ((base) + (0x0100))
#define SOC_MDC_CTL_MUTEX_WCH0_ADDR(base) ((base) + (0x0020))
#define SOC_MDC_WCH0_OV_IEN_ADDR(base) ((base) + (0x01A0))
#define SOC_MDC_WCH0_FLUSH_EN_ADDR(base) ((base) + (0x0120))
#define SOC_MDC_MOD8_DBG_ADDR(base) ((base) + (0x0220))
#define SOC_MDC_SCF_EN_HSCL_STR_ADDR(base) ((base) + (0x0200))
#define SOC_MDC_PCSC_IDC0_ADDR(base) ((base) + (0x0400))
#define SOC_MDC_POST_CLIP_DISP_SIZE_ADDR(base) ((base) + (0x0480))
#define SOC_MDC_CSC_IDC0_ADDR(base) ((base) + (0x0500))
#define SOC_MDC_MOD1_DBG_ADDR(base) ((base) + (0x0204))
#define SOC_MDC_MOD2_DBG_ADDR(base) ((base) + (0x0208))
#define SOC_MDC_MOD6_DBG_ADDR(base) ((base) + (0x0218))
#define SOC_MDC_MOD9_DBG_ADDR(base) ((base) + (0x0224))
#define SOC_MDC_MOD12_DBG_ADDR(base) ((base) + (0x0230))
#define SOC_MDC_CMDLIST_SWRST_ADDR(base) ((base) + (0x0738))
#define SOC_MDC_CTL_CLEAR_ADDR(base) ((base) + (0x0058))
#define SOC_MDC_CTL_STATUS_ADDR(base) ((base) + (0x0068))
#define SOC_MDC_DMA_BUF_DBG0_ADDR(base) ((base) + (0x838))
#define SOC_MDC_DMA_BUF_DBG1_ADDR(base) ((base) + (0x83C))
#define SOC_MDC_CTL_MUTEX_RCH1_ADDR(base) ((base) + (0x0034))
#define SOC_MDC_CTL_MUTEX_RCH2_ADDR(base) ((base) + (0x0038))
#define SOC_MDC_CTL_MUTEX_RCH6_ADDR(base) ((base) + (0x0048))
#define SOC_MDC_CTL_MUTEX_WCH1_ADDR(base) ((base) + (0x0024))
#define SOC_MDC_CMDLIST_CH_CTRL_ADDR(base,i) ((base) + (0x0004+0x40*(i)))
#define SOC_MDC_CMDLIST_CH_STATUS_ADDR(base,i) ((base) + (0x0008+0x40*(i)))
#define SOC_MDC_CMDLIST_CH_INTS_ADDR(base,i) ((base) + (0x001C+0x40*(i)))
#define SOC_MDC_CMDLIST_ADDR_MASK_EN_ADDR(base) ((base) + (0x0718))
#define SOC_MDC_CMDLIST_CH_STAAD_ADDR(base,i) ((base) + (0x000C+0x40*(i)))
#define SOC_MDC_CMDLIST_ADDR_MASK_DIS_ADDR(base) ((base) + (0x071C))
#define SOC_MDC_CTL_ST_SEL_ADDR(base) ((base) + (0x0074))
#define SOC_MDC_CTL_SW_ST_ADDR(base) ((base) + (0x0070))
#define SOC_MDC_AIF_CH_CTL_1_ADDR(base) ((base) + (0x0020))
#define SOC_MDC_AIF_CH_CTL_2_ADDR(base) ((base) + (0x0040))
#define SOC_MDC_AIF_CH_CTL_6_ADDR(base) ((base) + (0x00C0))
#define SOC_MDC_AIF_CH_CTL_8_ADDR(base) ((base) + (0x0100))
#define SOC_MDC_AIF_CH_CTL_9_ADDR(base) ((base) + (0x0120))
#define SOC_MDC_AIF_CH_CTL_10_ADDR(base) ((base) + (0x0140))
#define SOC_MDC_AIF_CH_CTL_CMD_ADDR(base) ((base) + (0x0830))
#define SOC_MDC_MMU_ID_ATTR_NS_0_ADDR(base) ((base) + (0x0580))
#define SOC_MDC_MMU_ID_ATTR_NS_1_ADDR(base) ((base) + (0x0584))
#define SOC_MDC_MMU_ID_ATTR_NS_2_ADDR(base) ((base) + (0x0588))
#define SOC_MDC_MMU_ID_ATTR_NS_6_ADDR(base) ((base) + (0x0598))
#define SOC_MDC_MMU_ID_ATTR_NS_8_ADDR(base) ((base) + (0x05A0))
#define SOC_MDC_MMU_ID_ATTR_NS_9_ADDR(base) ((base) + (0x05A4))
#define SOC_MDC_MMU_ID_ATTR_NS_10_ADDR(base) ((base) + (0x05A8))
#define SOC_SMMUv3_TBU_SMMU_TBU_SWID_CFG_ADDR(base,m) ((base) + ((m)*0x4+0x100))
#define SOC_MDC_MMU_ID_ATTR_NS_13_ADDR(base) ((base) + (0x05B4))
#endif
#ifdef __cplusplus
    #if __cplusplus
        }
    #endif
#endif
#endif
